### PR TITLE
fix IdentifyViewer: add default for innerRef prop

### PR DESCRIPTION
**Pull request by dominik-warch**
`innerRef` is optional but is called everytime in `componentDidMount` and `componentWillUnmoun`. The prop is introduced in 3272dec1 but only in `Identify.jsx`. FeatureSearch results crash with `TypeError: this.props.innerRef is not a function` because there the prop is not set.

This PR sets `innerRef` in `defaultProps` so code that utilizies the `IdentifyViewer` component without setting innerRef do not crash.

### CODE REVIEW

**Comment by manisandro** [comment]
Thanks!
